name: Build the artefact
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        go: [
          "1.18"
        ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go}}

      - name: Get Module dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -o gorundeck-ssh cmd/gorundeck-ssh/main.go

      - name: Package the artefact
        run: |
          pkg_version=$(echo $GITHUB_REF_NAME | cut -d'v' -f2)
          cp -rp package_ressources gorundeck-ssh-${pkg_version}-plugin
          cp -rp gorundeck-ssh gorundeck-ssh-${pkg_version}-plugin/contents
          ls -lartR gorundeck-ssh-${pkg_version}-plugin/
          zip -r gorundeck-ssh-${pkg_version}-plugin.zip gorundeck-ssh-${pkg_version}-plugin
          ls -lart .
          echo "###########"
          ls -alrt gorundeck-ssh-${pkg_version}-plugin.zip
          echo "package_name=gorundeck-ssh-${pkg_version}-plugin" >> $GITHUB_ENV
          echo "package_file=gorundeck-ssh-${pkg_version}-plugin.zip" >> $GITHUB_ENV
      

      - name: Upload Release Asset
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.package_name }}"
          path: "${{ env.package_file }}"
