name: Build the artefact
on: [push]
jobs:
  build:
    name: Build ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        go: [
          "1.17"
        ]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Build
        run: |
          go get -u golang.org/x/lint/golint
          OUT="$(go get -a)"; test -z "$OUT" || (echo "$OUT" && return 1)
          OUT="$(gofmt -l -d ./)"; test -z "$OUT" || (echo "$OUT" && return 1)
          OUT="$(golint ./...)"; test -z "$OUT" || (echo "$OUT" && return 1)
          go build